In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [23]:
print(x)

[['Indonesia' 30.0 28000.0]
 ['Malaysia' 45.0 45000.0]
 ['Singapore' 25.0 24000.0]
 ['Malaysia' 55.0 60000.0]
 ['Singapore' 40.0 nan]
 ['Indonesia' 33.0 35000.0]
 ['Malaysia' nan 40000.0]
 ['Indonesia' 29.0 29000.0]
 ['Singapore' 47.0 50000.0]
 ['Indonesia' 27.0 25000.0]]


In [24]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] =imputer.transform(x[:,1:3])

In [26]:
print(x)

[['Indonesia' 30.0 28000.0]
 ['Malaysia' 45.0 45000.0]
 ['Singapore' 25.0 24000.0]
 ['Malaysia' 55.0 60000.0]
 ['Singapore' 40.0 37333.333333333336]
 ['Indonesia' 33.0 35000.0]
 ['Malaysia' 36.77777777777778 40000.0]
 ['Indonesia' 29.0 29000.0]
 ['Singapore' 47.0 50000.0]
 ['Indonesia' 27.0 25000.0]]


In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [28]:
print(x)

[[1.0 0.0 0.0 30.0 28000.0]
 [0.0 1.0 0.0 45.0 45000.0]
 [0.0 0.0 1.0 25.0 24000.0]
 [0.0 1.0 0.0 55.0 60000.0]
 [0.0 0.0 1.0 40.0 37333.333333333336]
 [1.0 0.0 0.0 33.0 35000.0]
 [0.0 1.0 0.0 36.77777777777778 40000.0]
 [1.0 0.0 0.0 29.0 29000.0]
 [0.0 0.0 1.0 47.0 50000.0]
 [1.0 0.0 0.0 27.0 25000.0]]


In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [30]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [32]:
print(x_train)

[[0.0 1.0 0.0 36.77777777777778 40000.0]
 [0.0 0.0 1.0 40.0 37333.333333333336]
 [1.0 0.0 0.0 30.0 28000.0]
 [0.0 1.0 0.0 55.0 60000.0]
 [0.0 1.0 0.0 45.0 45000.0]
 [1.0 0.0 0.0 29.0 29000.0]
 [0.0 0.0 1.0 47.0 50000.0]
 [1.0 0.0 0.0 33.0 35000.0]]


In [33]:
print(x_test)

[[0.0 0.0 1.0 25.0 24000.0]
 [1.0 0.0 0.0 27.0 25000.0]]


In [34]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [35]:
print(y_test)

[0 1]


In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [37]:
print(x_train)

[[0.0 1.0 0.0 -0.31722561737955984 -0.05350972417829976]
 [0.0 0.0 1.0 0.062136976600120096 -0.3169422124406959]
 [1.0 0.0 0.0 -1.11519521161268 -1.2389559213590837]
 [0.0 1.0 0.0 1.8281352589193203 1.9222339377896736]
 [0.0 1.0 0.0 0.6508030707065201 0.44042619131369354]
 [1.0 0.0 0.0 -1.23292843043396 -1.140168738260685]
 [0.0 0.0 1.0 0.8862695083490801 0.9343621068056869]
 [1.0 0.0 0.0 -0.76199555514884 -0.547445639670293]]


In [38]:
print(x_test)

[[0.0 0.0 1.0 -1.7038613057190801 -1.6341046537526784]
 [1.0 0.0 0.0 -1.46839486807652 -1.5353174706542798]]
